=== PapaccioDeveloper/dam_ldm_act_03/valiDTD.dtd
<!ELEMENT pokemons (pokemon+)>
<!ELEMENT pokemon (nombre,codigo,foto,color,fuerza,comentario)>
<!ATTLIST pokemon tipo NMTOKEN #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre maxlength NMTOKEN #REQUIRED>
<!ELEMENT codigo (#PCDATA)>
<!ATTLIST codigo pattern NMTOKEN #REQUIRED>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT fuerza (#PCDATA)>
<!ELEMENT comentario (#PCDATA)>
<!ATTLIST comentario maxlength NMTOKEN #REQUIRED>

=== PapaccioDeveloper/dam_ldm_act_03/pokemonsVersionDTD.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE pokemons SYSTEM "valiDTD.dtd">

<pokemons>
    <pokemon tipo="Hielo">
        <nombre maxlength="10">Charizard </nombre>
        <codigo pattern="PK-">0001</codigo>
        <foto>/img/pokemon1</foto>
        <color>Azul</color>  
        <fuerza>23</fuerza>
        <comentario maxlength="50">Lorem ipsum</comentario>
    </pokemon>
    <pokemon tipo="Fuego">
        <nombre maxlength="10">Pikachu </nombre>
        <codigo pattern="PK-">0001</codigo>
        <foto>/img/pokemon2</foto>
        <color>Azul</color>  
        <fuerza>55</fuerza>
        <comentario maxlength="50">Lorem ipsum</comentario>
    </pokemon>
    <pokemon tipo="Agua">
        <nombre maxlength="10">Bulbasur </nombre>
        <codigo pattern="PK-">0001</codigo>
        <foto>/img/pokemon3</foto>
        <color>Rojo</color>  
        <fuerza>88</fuerza>
        <comentario maxlength="50">Lorem ipsum</comentario>
    </pokemon>

</pokemons>

=== PapaccioDeveloper/dam_ldm_act_03/pokemons.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- <!DOCTYPE pokemons SYSTEM "valiDTD.dtd"> -->

<pokemons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validar.xsd">
    <pokemon tipo="Hielo">
        <nombre >Charizard </nombre>
        <codigo >PK-0001</codigo>
        <foto>/img/pokemon1</foto>
        <color>Azul</color>  
        <fuerza>23</fuerza>
        <comentario >Lorem ipsum</comentario>
    </pokemon>
    <pokemon tipo="Fuego">
        <nombre >Pikachu </nombre>
        <codigo >PK-0001</codigo>
        <foto>/img/pokemon2</foto>
        <color>Azul</color>  
        <fuerza>55</fuerza>
        <comentario >Lorem ipsum</comentario>
    </pokemon>
    <pokemon tipo="Agua">
        <nombre >Bulbasur </nombre>
        <codigo >PK-0001</codigo>
        <foto>/img/pokemon3</foto>
        <color>Rojo</color>  
        <fuerza>88</fuerza>
        <comentario >Lorem ipsum</comentario>
    </pokemon>

</pokemons>
